on:
  push:
    tags:
      - "v*"

jobs:
  publish-binary:
    name: "Publish Binary to GitHub"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            # `toolchain: stable` results in the latest stable toolchain being installed.
            # However as soon as we use cargo the real version specified in rust-toolchain.toml replaces the stable toolchain.
            #
            # When something like https://github.com/actions-rs/toolchain/pull/184 lands we can delete this line and get a nice speedup
            profile: minimal
            toolchain: stable
      # - name: Install ubuntu packages
      #   run: scripts/install_ubuntu_packages.sh
      - name: Build & test
        run: scripts/build_release.sh
      - name: Publish
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            *.tar.gz
